version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: metrics-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana:8.4.5
    container_name: metrics-grafana
    ports:
      - "${GRAFANA_PORT}:3000"
