global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "sample-application"
    static_configs:
      - targets: [ "host.docker.internal:6050" ]
#  - job_name: "documents-parser"
#    static_configs:
#      - targets: [ "host.docker.internal:7200" ]